### PR TITLE
Support for aarch64 tracing

### PR DESCRIPTION
**Pull request by eiselekd**
Aarch64 uses GETREGSET and different reg array.

### CODE REVIEW

**Comment by socketpair** [comment]
@eiselekd are you tracing batctl ?

**Comment by socketpair** [comment]
I see, you tried to trace hostapd. But why ?

**Comment by eiselekd** [comment]
I'm trying to setup a AP using netlink only.

**Comment by socketpair** [comment]
@klukonin knows everything about it.

**Comment by klukonin** [comment]
Well. Currently it is possible to create only AP without any encryption with netlink (WEP is useless, let's say there is no encryption at all).
But it is not the only one limitation you will face with.
Hostapd (for example) does a lot of work for Handover, Management Frame Protection, Band steering, Dynamic Frequency Selection.
Even if you can set up an AP interface, you will be limited by just a dumb AP with no encryption scenario. Your service quality will be awful. No way.

**Comment by eiselekd** [comment]
@klukonin  Is there some code that you can share to do this? I'm trying it using pyroute2 and recreating 
a netlink trace aquired from hostapd. A working example to start with would be helpful. I dont 
mind the quality, it is more for development where I dont want to have hostapd in the way.

**Comment by klukonin** [comment]
@eiselekd 
Some BASH code can be found here
https://github.com/openwrt/openwrt/blob/1cd76e2d85d86356868db731a5cacfb84150b2a1/package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh
It's all iw based if we are talking about "no hostapd" solution.
iw use nl80211 for that, which is easy to strace and find what is going on.
Actually, we didn't dig deeper, because iw is enough for us.
But we'll be very appreciated  if this advice is helpful for you ))
May be you could look closer to this project: https://github.com/arend/py80211

**Comment by eiselekd** [comment]
@klukonin Ok thanks. I thought I knew netidd's mac80211.sh from openwrt and that it was creating hostapd's config. But maybe I missed some things. I'll take a look. Thanks.

**Pull request merged**
